### ISSUE TITLE
Server crash with World Edit

### ISSUE THREAD

**Issue by DonovanDau** [EngineHub/WorldEdit#2631] opened 2024-09-22 11:09 UTC
### WorldEdit Version

7.2.10

### Platform Version

Forge 4.2.21

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

*Hi,
Server is crashing as soon as I try to upload World Edit.
I migrated from Nitroserv to Omgserv, and it used to work. I can't comprehend why it isn't working anymore, and I don't know how to interpret the crash report, except the fact that it's supposed to be due to using World Edit.

Thanks for any help you might provide.

Best regards, 

https://pastebin.com/6suacpi2

### Expected Behavior

A normal start of the server

### Reproduction Steps

1. ...
2. ...
Just put World édit on the server with my actual mods

### Anything Else?

Work on nitroserv but not with omgserv

**Comment by me4502** [comment] 2024-09-22 11:11
duplicate of https://github.com/EngineHub/WorldEdit/issues/2522, and don't lie on the issue template.

**Closed by me4502** 2024-09-22 11:11 UTC
Labels: type:bug, status:pending

**Comment by DonovanDau** [comment] 2024-09-22 13:28
Oh sorry, i'm french i may do not have understood all the boxes for the
issues
Sorry about thad

Le dim. 22 sept. 2024 à 13:11, Maddy Miller ***@***.***> a
écrit :
