### ISSUE TITLE
Copy/Cut/Pasting carpet on top of carpet only copies the bottom most carpet

### ISSUE THREAD

**Issue by ChristopherHaws** [EngineHub/WorldEdit#2200] opened 2022-10-13 23:25 UTC
### WorldEdit Version

7.2.12-SNAPSHOT

### Platform Version

Purpur 1804 (MC 1.19.2)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When you have carpet on top of another carpet and try to cut/copy and paste using world edit, only the bottom most carpet is pasted. When cutting, the upper carpets are also dropped on the ground.

### Expected Behavior

The carpet's should be pasted along with the bottom carpet

### Reproduction Steps

1. Place a carpet on the ground
2. Place a carpet on the carpet
3. Select both blocks with your wand
4. Run `//cut` and notice that the top carpet drops on the floor
5. Run `//paste` and notice that only the bottom carpet is pasted

### Anything Else?

Here is a screenshot of the setup I am talking about in case it isn't clear :)

![image](https://user-images.githubusercontent.com/5934505/195728663-cb416264-3815-4c41-8650-ff187a58d34e.png)

**Comment by wizjany** [comment] 2022-10-13 23:36
duplicate of a million things. eg #2073

**Closed by wizjany** 2022-10-13 23:36 UTC
Labels: type:bug, status:pending
