### ISSUE TITLE
//setbiome not working in 1.16.1

### ISSUE THREAD

**Issue by SkaliberWasTaken** [EngineHub/WorldEdit#1422] opened 2020-07-06 10:10 UTC
Fabric Version: `0.6.1.45`

WorldEdit Version: `7.2.0-beta-01`

When using //setbiome to change the biome to soul_sand_valley, crimson_forest, warped_forest, or basalt_deltas, the biomes simply do not change. To clarify, this is after leaving and rejoining the world, and I am aware that biomes never change instantly in-game.

**Comment by octylFractal** [comment] 2020-07-06 10:11
Duplicate of #1399.

**Closed by octylFractal** 2020-07-06 10:11 UTC
Labels: status:pending, type:bug
