### ISSUE TITLE
Paintings in item frames don't get rotated, if item frame is on the top or bottom of a block

### ISSUE THREAD

**Issue by BSBMteam** [EngineHub/WorldEdit#1863] opened 2021-08-03 04:57 UTC
### WorldEdit Version

Fabric-Official(7.2.6-beta-02+2e45a20)

### Platform Version

Fabric 0.11.6-1.17

### Bug Description

Paintings on all item frame types (regular, invisible, and glow item frames) placed on the top and bottom of blocks don't get rotated. If you rotate the selection 90 degrees and paste it -e, the paintings don't get rotated 90 degrees.

These values set painting rotations in item frames:

ItemRotation: 0b = North
ItemRotation: 1b = East
ItemRotation: 2b = South
ItemRotation: 3b = West
ItemRotation: 4b = North
ItemRotation: 5b = East
ItemRotation: 6b = South

Maybe by default, //rotate automatically rotates item frame paintings. Then, add a separate option to retain painting rotations when pasting.

### Expected Behavior

If you copy -e, rotate a selection with paintings 90 degrees and paste it -e, the paintings should get rotated 90 degrees.

### Reproduction Steps

1. Place any painting on any item frame type (regular, invisible, and glow item frames) on the top or bottom of a block.
2. Select region that includes the painting.
3. //copy -e
4. //rotate 90 (you can do //rotate 180 OR //rotate 270)
5. //paste -e

**Comment by octylFractal** [comment] 2021-08-03 05:05
Duplicate of #1727

**Closed** 2021-08-03 05:05 UTC
Labels: status:pending, type:bug
