### ISSUE TITLE
//schem save shows large error string

### ISSUE THREAD

**Issue by Jazz-Hammer** [EngineHub/WorldEdit#2593] opened 2024-08-01 10:01 UTC
### WorldEdit Version

7.3.5

### Platform Version

Fabric-Official (7.3.5+6880-8ba3d89)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

"//schematic save", "//schem save","/schematic save","/schem save" show error string whenever using them. (only tested single player)
![image_2024-08-01_195927289](https://github.com/user-attachments/assets/17b28915-b8c2-4ba2-863b-a583836a8efb)

### Expected Behavior

saves the copied structure as a schematic

### Reproduction Steps

1. 
![image](https://github.com/user-attachments/assets/6471d11e-b404-4372-a6f2-cffa625414fd)

2. 
![image](https://github.com/user-attachments/assets/1237a524-7e4b-4c92-8bc3-e1225d8ce246)

**Comment by me4502** [comment] 2024-08-01 10:47
Duplicate of https://github.com/EngineHub/WorldEdit/issues/2586

**Closed by me4502** 2024-08-01 10:47 UTC
Labels: type:bug, status:pending
