### ISSUE TITLE
 Exception: java.lang.NoSuchMethodError using //regen

### ISSUE THREAD

**Issue by BenjaminGoGurts** [EngineHub/WorldEdit#1907] opened 2021-09-28 15:17 UTC
### WorldEdit Version

7.2.6

### Platform Version

git-Paper-259 (1.17.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

You select your positions with the worldedit wand or //pos1 and //pos2, then you type //regen you get an error in console and in chat

### Expected Behavior

The area should be regenerated 

### Reproduction Steps

1. Select your position using //wand
2. Type //regen
3.  Error appears

### Anything Else?

Stacktrace:
[15:14:47 INFO]: BenjaminGoGoose issued server command: //regen
[15:14:47 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NoSuchMethodError: 'void net.minecraft.server.level.WorldServer.<init>(net.minecraft.server.MinecraftServer, java.util.concurrent.Executor, net.minecraft.world.level.storage.Convertable$ConversionSession, net.minecraft.world.level.storage.IWorldDataServer, net.minecraft.resources.ResourceKey, net.minecraft.world.level.dimension.DimensionManager, net.minecraft.server.level.progress.WorldLoadListener, net.minecraft.world.level.chunk.ChunkGenerator, boolean, long, java.util.List, boolean, org.bukkit.World$Environment, org.bukkit.generator.ChunkGenerator)'
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2.doRegen(Spigot_v1_17_R1_2.java:625) ~[worldedit-bukkit-7.2.6-beta-02.jar:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2.regenerate(Spigot_v1_17_R1_2.java:578) ~[worldedit-bukkit-7.2.6-beta-02.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:216) ~[worldedit-bukkit-7.2.6-beta-02.jar:?]
        at com.sk89q.worldedit.command.RegionCommands.regenerate(RegionCommands.java:431) ~[worldedit-bukkit-7.2.6-beta-02.jar:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:576) ~[worldedit-bukkit-7.2.6-beta-02.jar:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-bukkit-7.2.6-beta-02.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[worldedit-bukkit-7.2.6-beta-02.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-7.2.6-beta-02.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.6-beta-02.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.6-beta-02.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.2.6-beta-02.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[worldedit-bukkit-7.2.6-beta-02.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.2.6-beta-02.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-231]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2182) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1993) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1974) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1363) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1342) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1335) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1296) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1207) ~[patched_1.17.1.jar:git-Paper-231]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[patched_1.17.1.jar:git-Paper-231]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by octylFractal** [comment] 2021-09-28 16:05
Please read the pinned issues. Duplicate of #1872

**Closed by octylFractal** 2021-09-28 16:05 UTC
Labels: type:bug, status:pending
