### ISSUE TITLE
When you //sel to deselect, you get kicked due to packet size "larger than I expected"

### ISSUE THREAD

**Issue by WithLithum** [EngineHub/WorldEdit#2528] opened 2024-05-15 09:01 UTC
### WorldEdit Version

7.3.1+6763-2e55f4f

### Platform Version

Fabric (loader 0.15.11, API 0.98.0+1.20.6)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Whenever you run `//sel` to clear selection, you get kicked (even in Singleplayer) due to:
```
Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/clientbound/minecraft:custom_payload (class_2658) was larger than I expected, found 8 bytes extra whilst reading packet clientbound/minecraft:custom_payload
```

### Expected Behavior

You should not get kicked for using `//sel`.

### Reproduction Steps

1. Make a region selection.
2. Type `//sel`.
3. You get kicked due to `Internal Exception: io...`

### Anything Else?

- I have tested with only Fabric API and WorldEdit, at the client side, in a single-player world, and this issue is still occurring.
- This may be the same issue as of #2525 but this clearly matches the description of a comment under it.

**Comment by me4502** [comment] 2024-05-15 10:32
Duplicate of https://github.com/EngineHub/WorldEdit/issues/2525

**Closed by me4502** 2024-05-15 10:32 UTC
Labels: type:bug, status:pending
