### ISSUE TITLE
Hopper's connected to chest are not getting pasted.

### ISSUE THREAD

**Issue by piyushmanolkar** [EngineHub/WorldEdit#1637] opened 2021-01-04 10:09 UTC
Minecraft 1.16.4
Forge 35.1.28
WorldEdit 7.2.1+299386a

EDIT - After reopening the world the hoppers are loaded, therefore the hopper's are getting pasted, but the texture doesn't appear when pasted, I'll still consider this a bug and keep this issue open.

1. Image of the original structure - 
![image](https://user-images.githubusercontent.com/36564289/103523989-d4fdbf80-4ea2-11eb-847c-238a16420a69.png)

2. Image after pasting - 
![image](https://user-images.githubusercontent.com/36564289/103524081-f6f74200-4ea2-11eb-8442-8a4a674eddee.png)

**Comment by octylFractal** [comment] 2021-01-04 10:22
If they're not appearing it's likely you disabled some //perf options or it's some sort of MC bug. Do you have a schematic we can use to reproduce?

**Comment by piyushmanolkar** [comment] 2021-01-04 13:40
I haven't fiddled with any perf options, everything is default, I'll post a schematic file ASAP.

**Comment by jrgogolin8** [comment] 2021-01-08 00:09
Problem happens when pasting powered hoppers not just hoppers connected to chests, if you leave the game and rejoin should show up after.

**Comment by octylFractal** [comment] 2021-03-09 02:21
Haven't had time to investigate, and also still don't have a schematic for reproduction purposes. Might look eventually, but won't mark accepted for now.

**Comment by iansebryk** [comment] 2021-04-22 22:50
can confirm this is happening.  if you take the [item sorter](https://www.youtube.com/watch?v=2npoihZswms), for example, and try stacking it, the hoppers going in to chests will not be copied through the stack.

**Comment by octylFractal** [comment] 2021-06-01 19:17
Marking this as help-wanted, not a high priority right now since it's just visual and that might not even be a bug on our end, but Minecraft's.

**Comment by octylFractal** [comment] 2024-05-09 19:32
This seems like nothing we can fix here, and isn't reproducible now.

**Closed by octylFractal** 2024-05-09 19:32 UTC
Labels: type:bug, status:good-first-issue
