### ISSUE TITLE
Beds and doors will not copy/paste/stack etc

### ISSUE THREAD

**Issue by NJDaeger** [EngineHub/WorldEdit#1279] opened 2020-04-02 15:47 UTC
**Versions**
WorldEdit version: Bukkit-Official(7.2.0-SNAPSHOT+4947-404feef)
Platform version: git-Paper-221 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Describe the bug**
Whenever I copy, paste, or stack doors and beds, nothing is changed.

**To Reproduce**
1. Place some beds and doors down
2. Select them and copy
3. Paste them or stack your selection.

**Expected behavior**
When you select beds and doors, they should be able to be copied and pasted or stacked.

**Screenshots**
![2020-04-02_11 38 29](https://user-images.githubusercontent.com/18237863/78269481-a9931200-74d7-11ea-844d-ee602ddf4fd6.png)
![2020-04-02_11 38 53](https://user-images.githubusercontent.com/18237863/78269521-b44da700-74d7-11ea-9ee7-21b185f1f507.png)

**Comment by wizjany** [comment] 2020-04-02 16:00
Notably, to reproduce this you need the exact setup shown in the screenshot. Beds alone, doors alone, and beds not in front of doors all work fine. Only issue is when the door is directly behind the bed.

**Comment by me4502** [comment] 2021-08-22 06:29
Due to WorldEdit 7.3.0 defaulting to `//reorder fast`, this is resolved. It's most likely an issue with the multi-stage reorder system that probably cannot be easily fixed. Therefore fast reorder is probably the best solution here anyway. Closing as it's "fixed by default"

**Closed by me4502** 2021-08-22 06:29 UTC
Labels: type:bug, status:accepted
