### ISSUE TITLE
[Bug] Commands like //thaw do not work.

### ISSUE THREAD

**Issue by Kingdomall** [EngineHub/WorldEdit#1321] opened 2020-04-28 23:14 UTC
Minecraft 1.15.2 Forge, 
WorldEdit version: Release WorldEdit-forge-mc1.15.2-7.1.0
Platform version: 1.15.2 Forge 31-1-41

Commands like "//thaw" break the use of commands. After applying it, it not only doesn't work but it also ignores all commands including //wand.
The only command that works is //wand and the ones that tie into it, like //replace and //set. Some other commands like //move work and //brush does not. 

**To Reproduce**
1. Enter a world and simply enter //thaw (any number)
2. The same applies to a few other commands

snow and ice around the player would disappear within the radius that the number gave like in previous versions.

Instead of screenshots, I will provide a log for every time I recreated this. I attempted at least three times (ending the MC process every time).
[2020-04-28-3.log.gz](https://github.com/EngineHub/WorldEdit/files/4549027/2020-04-28-3.log.gz)
[2020-04-28-2.log.gz](https://github.com/EngineHub/WorldEdit/files/4549028/2020-04-28-2.log.gz)
[2020-04-28-1.log.gz](https://github.com/EngineHub/WorldEdit/files/4549029/2020-04-28-1.log.gz)

**Comment by wizjany** [comment] 2020-04-28 23:49
outside of you removing the snow realm magic mod which is causing a lot of things to be very unhappy, it's unclear what the actual WE issue is. The only thing you've said are that commands "break" or are "ignored" which manage to be both completely ambiguous and contradictory at the same time.

**Comment by Kingdomall** [comment] 2020-04-29 00:52
Oh I removed that mod shortly after, I must have left that log out. It still didn't work after I removed the mod.
[2020-04-28-4.log.gz](https://github.com/EngineHub/WorldEdit/files/4549279/2020-04-28-4.log.gz)

**Comment by wizjany** [comment] 2020-04-29 01:07
You still haven't elaborated whatsoever on what doesn't work. Please provide proper reproduction steps or a video or something useful. Closing the issue for now since thaw (and subsequent commands) are working just fine for me.

**Closed by wizjany** 2020-04-29 01:07 UTC
Labels: status:pending, type:bug
