### ISSUE TITLE
Minecraft shows “connection lost” when running //sel In single player 

### ISSUE THREAD

**Issue by Wongyinting** [EngineHub/WorldEdit#2532] opened 2024-05-18 07:47 UTC
### WorldEdit Version

7.3.1+6763-2e55f4f

### Platform Version

Fabric 0.15.11

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

In Minecraft 1.20.6, When typing “//sel” into the chat, a “connection lost” page appears. I am playing in single player but not multiplayer

### Expected Behavior

Clear the selection

### Reproduction Steps

1. Log in a single player world
2. Type “//sel” in chat
3.  The “Connection lost” page appears

### Anything Else?

I am not using worldedit cui
System Windows 11 Pro
AMD Ryzen with Radeon graphics
Default launcher
Installed mods: 
Sodium 
Iris
Mod menu
Euphoria patches
continuity
Indium

**Comment by Wongyinting** [comment] 2024-05-18 07:49
https://github.com/EngineHub/WorldEdit/assets/170166523/9d4d4ff4-6844-4bd5-875e-ce0366f741ba

**Comment by Wongyinting** [comment] 2024-05-18 07:51
![image](https://github.com/EngineHub/WorldEdit/assets/170166523/2873ed09-25f3-45e6-b2d2-c18b65ed18f2)

**Comment by me4502** [comment] 2024-05-18 07:51
Duplicate of https://github.com/EngineHub/WorldEdit/issues/2525

in general though this is not an issue i can reproduce. if you can provide any extra information to help reproduce it that'd be appreciated, as i can't identify the issue if i can't trigger it myself

**Closed** 2024-05-18 07:51 UTC
Labels: type:bug, status:invalid
