### ISSUE TITLE
CuresForge Fabric 0.11.6 Says WorldEdit Is Incompatible

### ISSUE THREAD

**Issue by NotMinecraftManiac** [EngineHub/WorldEdit#1894] opened 2021-09-11 12:39 UTC
### WorldEdit Version

7.2.6

### Platform Version

Fabric 0.11.6

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

What happens is on the curse forge app I created a loader and added world edit and it said it was incompatible with your loader. when I downloaded the recommended version and the one for both forge and fabric for 1.17.1. It just doesn't make sense to me.
![2021-09-11](https://user-images.githubusercontent.com/89983614/132948004-45bbf8c9-b09a-404f-b990-ab7d1dd92fa9.png)
There is a picture of it.

### Expected Behavior

I expected it to work all normally and I could use worldedit in my builds. But this is what happened.

### Reproduction Steps

1. Open CurseForge
2. Add WorldEdit 7.2.6 to FABRIC 0.11.6
3. Hover over the yellow warning triangle and read the text
4. That is the thing that's happening.

### Anything Else?

Just one question thats to do with this bug. Is this usual or just for me? Because I can't find it on GitHub issues at all.

**Comment by me4502** [comment] 2021-09-11 12:57
This is a CurseForge issue, there's not really anything we can do about this

**Comment by wizjany** [comment] 2021-09-11 13:02
Duplicate of #1879

**Closed by wizjany** 2021-09-11 13:02 UTC
Labels: type:bug, status:pending
