### ISSUE TITLE
Worldedit bukkit v7.2.0 b2 //regen server crash

### ISSUE THREAD

**Issue by Cwoodyard** [EngineHub/WorldEdit#1484] opened 2020-08-12 21:07 UTC
**Versions**

WorldEdit version: 7.2.0b2 bukkit
Platform version: java 1.16.2 spigot

**Describe the bug**

When I //regen an area over 6kish blocks the edit shows then the server will freeze for a few seconds and crashes.

**To Reproduce**

1. select area over 6k blocks
2. //regen
3. server crash

**Expected behavior**

For the worldedit to stay and the server not to crash

**Screenshots**

**Additional context**
Console log: 
[worldEditConsoleLog.txt](https://github.com/EngineHub/WorldEdit/files/5065717/worldEditConsoleLog.txt)

**Comment by octylFractal** [comment] 2020-08-12 21:10
Please reproduce with beta 03. I think there may have been changes which fix this.

**Comment by octylFractal** [comment] 2020-08-12 21:11
Additionally, this is technically a duplicate of #1313, since the root issue would be the same. Please report there if you still experience it with beta 03.

**Closed by octylFractal** 2020-08-12 21:11 UTC
Labels: status:pending, type:bug
