### ISSUE TITLE
any build command puts out an error

### ISSUE THREAD

**Issue by smikkelbakje** [EngineHub/WorldEdit#2019] opened 2022-01-26 18:21 UTC
### WorldEdit Version

 WorldEdit version 7.2.8

### Platform Version

Bukkit-Official(7.2.8+6008-1246d61)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

when i try to use any command it puts out an error
here i used //copy
https://pastebin.com/ZpQDdHLb

### Expected Behavior

i expected it to copy the thing so i could paste it later

### Reproduction Steps

1. ... install bukkit
2. ... put worldedit in plugin folder
3. put in any build command
4. it puts out this error

**Comment by smikkelbakje** [comment] 2022-01-26 18:25
the expirimental version works perfectly fine

**Comment by octylFractal** [comment] 2022-01-26 18:47
read the damn pinned issues smhing my head

**Comment by octylFractal** [comment] 2022-01-26 18:47
Duplicate of #1972

**Closed by octylFractal** 2022-01-26 18:47 UTC
Labels: type:bug, status:pending
