### ISSUE TITLE
minecraft 1.18.1 craftbukkit server error

### ISSUE THREAD

**Issue by nyangkkun** [EngineHub/WorldEdit#1996] opened 2022-01-01 12:48 UTC
### WorldEdit Version

7.2.8

### Platform Version

craftbukkit-1.18.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

worldedit not working

### Expected Behavior

is 3blocks set air

### Reproduction Steps

1.....
2.....

**Comment by JOO200** [comment] 2022-01-01 12:49
No logs but most likely duplicate of https://github.com/EngineHub/WorldEdit/issues/1972

**Closed** 2022-01-01 17:03 UTC
Labels: type:bug, status:pending
