### ISSUE TITLE
Crashes with 7.2.18 with //sel command

### ISSUE THREAD

**Issue by Daft785** [EngineHub/WorldEdit#2468] opened 2024-02-16 23:51 UTC
### WorldEdit Version

7.2.18

### Platform Version

forge 

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When i type in the //sel convex (or any type of sel) command i get kicked from my singleplayer world and onto the multiplayer servers list, along with a message "connection lost internal exeption: java.lang.nullpointerexeption

### Expected Behavior

the selections to be in convex mode

### Reproduction Steps

im not too sure, just logged on and did the //sel convex command.

### Anything Else?

asked on the discord and tried 7.2.19 and that completely crashes the game, no other mods are installed and no problems in general game play or with any other worldedit commands

**Comment by Daft785** [comment] 2024-02-16 23:53
sorry i forgot to mention forge version 49.0.22

**Comment by me4502** [comment] 2024-02-17 00:39
Duplicate of #2464. This is also a forge bug, not a worldedit bug. It's reproducible on a clean forge install without worldedit installed by connecting to a server

**Closed** 2024-02-17 00:39 UTC
Labels: type:bug, status:invalid
