### ISSUE TITLE
Blocks drop additionally V2

### ISSUE THREAD

**Issue by RobZenTL** [EngineHub/WorldEdit#1586] opened 2020-11-16 16:34 UTC
**Versions**
WorldEdit version: WorldEdit version 7.2.0 (latest)
Platform version: Paper version git-Paper-655 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Describe the bug**
After setting some blocks, the same blocks that were placed occur additional as dropped items. So the blocks are set, but they also are dropped as items.
Example: We are doing '//set stone' (or '1') and 9 cobblestone are dropped. But the 9 stone are also placed as cleanstone.
That also happens on an empty server with just WorldEdit installed.

**To Reproduce**
1. Copy and paste (or just set) any blocks

**Expected behavior**
The blocks that were set or pasted shouldn't appear additionally as dropped items

**Screenshots**
Video: https://youtu.be/RDYLKi9NjG8

**Comment by wizjany** [comment] 2020-11-16 16:53
looks like it might have been caused by https://github.com/EngineHub/worldedit-adapters/commit/95fde296b8d6de7b6b8f973f4637d77d412eb220#diff-5ae373a36862f0fbab41d5a196a02200c6973bc976bae13e24608c44c906ef7aR69
as that's the only change i can see between beta4 and beta5 to the 1.13.2 adapter.

**Comment by octylFractal** [comment] 2020-11-16 19:51
Going to close this as we only support the latest version of Minecraft. If it can be reproduced in 1.16.4, then we can re-open, or if someone would like to do the detective work themselves and PR the adapters repository we will also accept that.

**Closed by octylFractal** 2020-11-16 19:51 UTC
Labels: status:pending, type:bug
