### ISSUE TITLE
Allays count as hostile mobs using /butcher

### ISSUE THREAD

**Issue by Lucyndi** [EngineHub/WorldEdit#2259] opened 2023-02-05 17:46 UTC
### WorldEdit Version

7.2.14-SNAPSHOT+6290-474c191

### Platform Version

git-Paper-386

### Confirmations

- [x] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When using /butcher on hostile mobs, it includes allays. 

### Expected Behavior

Allays should not be removed when butchering hostiles, they are considered passive in vanilla

### Reproduction Steps

1. observe allay
2. /butcher
3. Observe allay dying

**Comment by octylFractal** [comment] 2023-02-05 17:52
Duplicate of #2168

**Closed by octylFractal** 2023-02-05 17:52 UTC
Labels: type:bug, status:pending
