### ISSUE TITLE
//regen dosen't work

### ISSUE THREAD

**Issue by halberfan** [EngineHub/WorldEdit#1893] opened 2021-09-11 10:17 UTC
### WorldEdit Version

WorldEdit 7.2.6+4b2d1e7

### Platform Version

git-Paper-243

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I want to use //regen on a world with a custom worldgenerator I get an error and it dosen't regenerate the world

https://pastebin.com/VhxcAM1W

### Expected Behavior

Normally, it should just regenerate the selected area

### Reproduction Steps

1. Mark Area
2. Use //regen

### Anything Else?

I tried it with two diffrent world generation plugins and in a normal world (generated with multiverse) in which I got the same error. I don't know if you can help me with it, but it says "Please report this error" so I just did it 😄

**Comment by JOO200** [comment] 2021-09-11 10:19
Duplicate of #1872

**Comment by halberfan** [comment] 2021-09-11 10:31
K, I got the newest dev build, but now I just get a diffrent error. Should I open a new Issue or just post it here?

**Comment by wizjany** [comment] 2021-09-11 13:00
preferably use discord since it's unlikely there's an actual bug

**Closed** 2021-09-11 13:00 UTC
Labels: type:bug, status:invalid
