### ISSUE TITLE
Crash during SP world creation

### ISSUE THREAD

**Issue by skies912** [EngineHub/WorldEdit#1695] opened 2021-03-08 17:38 UTC
**Versions**
WorldEdit version:  7.2.3 Forge/Fabric
Platform version: Forge 36.0.42, MultiMC 5.x
Java: OpenJDK 15.x / jre1.8.0_281
OS: Windows 10 x64 20H2

**Describe the bug**
MC 1.16.5 crashes during creation of single-player world.

**To Reproduce**
1. Launch brand new 1.16.5 Forge instance with ONLY worldedit-mod-7.2.3.jar
2. Singleplayer >> create new world
3. Create new world >> wait for crash

**Expected behavior**
World completely loads, enter world.

**Screenshots**
n/a

**Additional context**
Crash log:
[crash-report_worldedit.txt](https://github.com/EngineHub/WorldEdit/files/6103099/crash-report_worldedit.txt)

The odd thing about this bug is that it didn't used to occur - even with newest version of forge (.46)  - so, I have no idea what's going on now. Seems to work fine during MP.

**Comment by octylFractal** [comment] 2021-03-08 17:40
would it kill ya to read pinned issues

Duplicate of #1398

**Closed by octylFractal** 2021-03-08 17:40 UTC
Labels: status:pending, type:bug

**Comment by skies912** [comment] 2021-03-08 17:42
Whoops, sorry about that!
