### ISSUE TITLE
Very high memory usage with blocks with multiple states

### ISSUE THREAD

**Issue by PoIyframeX** [EngineHub/WorldEdit#2567] opened 2024-07-03 23:21 UTC
### WorldEdit Version

7.2.15

### Platform Version

Neoforge 21.0.53

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When having many mods with many block states (such as for example combined with every compat and chipped) the game can use heavy amounts of ram usage sometimes being 3gb for just loading the game. It's a serious issue that makes worldedit unusable when with many blocks.

### Expected Behavior

The game should have little ram increase.

### Reproduction Steps

1. Download worldedit
2. Download any mod that increase blocks alot (such as chipped, everycompat, regions unexplored)
3. See the ram usage go up significantly

### Anything Else?

This issue is verified to be an issue on world edits end. As every compat usually only increases ram by 0.6gb. Even on very high amounts of mods. However the moment world edits installed. This number jumps significantly. Causing the game to lag and in many cases, be unplayable.

**Comment by me4502** [comment] 2024-07-03 23:26
duplicate of https://github.com/EngineHub/WorldEdit/issues/2488, and don't lie on the issue template.

mods like WorldEdit inherently need to know what block states exist, it takes a tiny tiny amount of memory normally and can scale extremely far as long as the concept of states aren't being abused. For it to be as large as you're describing, one of the other mods you're using must be abusing block states very badly. Minecraft is not built to have billions of block states, NBT data is meant to be used for anything that's going to inflate to tens of millions of states.

**Closed by me4502** 2024-07-03 23:26 UTC
Labels: type:bug, status:pending
