### ISSUE TITLE
Redstone Breaking

### ISSUE THREAD

**Issue by sgort87** [EngineHub/WorldEdit#2630] opened 2024-09-19 20:17 UTC
### WorldEdit Version

All 1.21 versions

### Platform Version

Fabric

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Redstone is breaking when moved or cut (not copy). Possibly happening with other functions.

### Expected Behavior

Redstone should stay in tact when moved or cut with supporting blocks.

### Reproduction Steps

1. Select redstone and supporting blocks.
2. Cut & paste, or move selection.
3. Be frustrated.

### Anything Else?

Tested with all 1.21 versions of the mod in Fabric 1.21 and 1.21.1 both single player and server, no other mods.

Thanks for your help. <3

**Comment by octylFractal** [comment] 2024-09-19 20:19
Duplicate of #2516

**Closed by octylFractal** 2024-09-19 20:19 UTC
Labels: type:bug, status:pending
