### ISSUE TITLE
//setbiome not working in 1.16, WE 7.2.0, Fabric; offline

### ISSUE THREAD

**Issue by nachimir** [EngineHub/WorldEdit#1418] opened 2020-07-03 19:11 UTC
**Versions**
WorldEdit version: 7.2.0-beta-01)
Platform version: Fabric-Official(7.2.0-beta-01+0eb9ac7)

**Describe the bug**
//setbiome command reports success, but nothing changes visually, 
Have tried waiting a while, leaving and rejoining.
Have tried testing it on small areas instead of large.
Have tried changing desert to forest and flower_forest.
Have tried biome names with and without 'minecraft:' prefix
/biomeinfo shows whatever I tried to change it to - so something is updating
F3 still shows original biome information, even if /biomeinfo contradicts it

**To Reproduce**
Use wand to make selection, use /setbiome to change biome. Wait a short while, leave game, reload.

**Expected behavior**
Biome should be changed but is not.

**Comment by octylFractal** [comment] 2020-07-03 19:17
Duplicate of #1399.

**Closed by octylFractal** 2020-07-03 19:17 UTC
Labels: status:pending, type:bug
