### ISSUE TITLE
//regen doesn't work for 1.17.1

### ISSUE THREAD

**Issue by GroGaloraGran** [EngineHub/WorldEdit#1884] opened 2021-08-31 17:56 UTC
### WorldEdit Version

WorldEdit-bukkit-7.2.6

### Platform Version

paper-231 (1.17.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Hey
I try to run //regen for the selected area, but I get an error:

`[21:04:46] [Server thread/INFO]: GroGaloraGran issued server command: //regen
[21:04:46] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NoSuchMethodError: 'void net.minecraft.server.level.WorldServer.<init>(net.minecraft.server.MinecraftServer, java.util.concurrent.Executor, net.minecraft.world.level.storage.Convertable$ConversionSession, net.minecraft.world.level.storage.IWorldDataServer, net.minecraft.resources.ResourceKey, net.minecraft.world.level.dimension.DimensionManager, net.minecraft.server.level.progress.WorldLoadListener, net.minecraft.world.level.chunk.ChunkGenerator, boolean, long, java.util.List, boolean, org.bukkit.World$Environment, org.bukkit.generator.ChunkGenerator)'
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2.doRegen(Spigot_v1_17_R1_2.java:625) ~[worldedit-bukkit-7.2.6.jar:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2.regenerate(Spigot_v1_17_R1_2.java:578) ~[worldedit-bukkit-7.2.6.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:216) ~[worldedit-bukkit-7.2.6.jar:?]
	at com.sk89q.worldedit.command.RegionCommands.regenerate(RegionCommands.java:431) ~[worldedit-bukkit-7.2.6.jar:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:576) ~[worldedit-bukkit-7.2.6.jar:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-bukkit-7.2.6.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[worldedit-bukkit-7.2.6.jar:?]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.2.6.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.6.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.6.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.2.6.jar:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[worldedit-bukkit-7.2.6.jar:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.2.6.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-231]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2182) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1993) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1974) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1363) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1342) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1335) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1473) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1203) ~[patched_1.17.1.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[patched_1.17.1.jar:git-Paper-231]
	at java.lang.Thread.run(Thread.java:831) [?:?]
`
I am testing the transition from 1.16.5 to 1.17.1 and checking the work of plugins

### Expected Behavior

when entering the command //regen, the allocated zone should be restored

### Reproduction Steps

1, enter the world 1.17.1
2, select the area required for recovery
3, enter command
4, get error

**Comment by octylFractal** [comment] 2021-08-31 17:57
Duplicate of #1872

**Closed by octylFractal** 2021-08-31 17:57 UTC
Labels: type:bug, status:pending
