### ISSUE TITLE
World doesn't load on lunar client

### ISSUE THREAD

**Issue by sepprsd** [EngineHub/WorldEdit#2556] opened 2024-06-21 06:29 UTC
### WorldEdit Version

WorldEdit 7.3.4 Beta 1 (NeoForge/Fabric for MC 1.21)

### Platform Version

lunar client 1.21 - fabric

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When i load in a world, i get this disconnect error:

![afbeelding_2024-06-21_083047415](https://github.com/EngineHub/WorldEdit/assets/142796193/ea05b6de-d838-4486-84a9-28538ef69d36)

i am not using any other mods, exept for the build in lunar client mods. i also find it wierd how i can disconnect, while i am on singleplayer.

Log:
[disconnect-2024-06-21_08.13.50-client.txt](https://github.com/user-attachments/files/15923563/disconnect-2024-06-21_08.13.50-client.txt)

### Expected Behavior

just load in the world as normal

### Reproduction Steps

1. open lunar client.
2. click on 1.21 and then settings for 1.21.
3. then click on mods and open mods folder.
4. load the worldedit file in the folder.
5. launch lunar client.
6. open a 1.21 single player world (that was created in vaniala minecraft).

**Comment by me4502** [comment] 2024-06-21 06:32
If Lunar client is causing an issue with mods, which I've seen mentioned a few times in the past few days, this is something they need to fix. If you can reproduce the error without Lunar client then it's something we can look at

**Comment by sepprsd** [comment] 2024-06-21 06:32
ok, i will try

**Comment by me4502** [comment] 2024-07-21 05:28
This is something Lunar must fix. Only one mod at a time can register channels, and Lunar is for some reason deciding to register the worldedit one which means when WorldEdit is installed it'll fail due to two mods registering the same channel. Given the worldedit channel is very clearly intended to be used by WorldEdit, Lunar should stop trying to register it. We can't stop registering it because it's our channel.

Closing this as there's nothing we can do on our end, this is purely a Lunar issue that only they can fix.

**Closed by me4502** 2024-07-21 05:28 UTC
Labels: type:bug, status:pending
