### ISSUE TITLE
Left click "jump to" with compass is not working

### ISSUE THREAD

**Issue by Fixer-007** [EngineHub/WorldEdit#1490] opened 2020-08-14 16:04 UTC
**Versions**

WorldEdit version: WorldEdit 7.2.0 Beta 3 (Fabric for MC 1.16.1)
Platform version: Fabric 0.9.1-build.205

**Describe the bug**
Left click "jump to" not working.

**To Reproduce**
//wand -n to give yourself a compass, try left clicking with it to some distant terrain, it will not teleport you, if you point to smth within player's reach it will teleport you fine. Right click teleport through is working fine. Creative mode, cheats enabled.

**Comment by Vaelot** [comment] 2020-08-16 11:41
I think this is for fabric-specific bug from commit a0b4f9330, which deletes left button event.
I'm curious about why they delete those event code, but anyway after revert it, it works fine for me. I'll pull the request soon.

**Comment by booski** [comment] 2020-12-27 14:23
I'm experiencing this bug as well. It worked fine under Forge 35.1.15, but is broken under Fabric 0.6.1.51

Worldedit version: 7.2.1
MC version: 1.16.4

**Comment by octylFractal** [comment] 2021-01-03 20:52
Duplicate of #1439.

**Closed by octylFractal** 2021-01-03 20:52 UTC
Labels: status:pending, type:bug
