### ISSUE TITLE
Schematic System Won't Work

### ISSUE THREAD

**Issue by MrCake21** [EngineHub/WorldEdit#2596] opened 2024-08-07 18:35 UTC
### WorldEdit Version

7.3.5

### Platform Version

Fabric-Official(7.3.5+6880-8ba3d89

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Whenever I try to save, load, or even find the list of current schematic files in my minecraft world, it doesn't work and says to report the error
![2024-08-07_13 32 27](https://github.com/user-attachments/assets/f10618c4-903a-4c33-9c84-a96627cb2c78)

It also gives me other versions for types of files, I assume these are mean't to be here but just in case I'll mention it
![2024-08-07_13 34 22](https://github.com/user-attachments/assets/2350b890-ff82-4895-85d5-6511f071fc25)

### Expected Behavior

The schematic system should be able to work, I'm just not sure why as it has worked in the past with a different world edit version

### Reproduction Steps

#1. Load Up Minecraft
#2 Open Up World
#3 Type in /schem or /schematic followed by anything

### Anything Else?

If this is somehow on my end I'm sorry for wasting your time!

**Comment by octylFractal** [comment] 2024-08-07 18:38
Duplicate of #2586

**Closed by octylFractal** 2024-08-07 18:38 UTC
Labels: type:bug, status:pending
