### ISSUE TITLE
trees stack on top of each other

### ISSUE THREAD

**Issue by NightDust12** [EngineHub/WorldEdit#2199] opened 2022-10-03 00:05 UTC
### WorldEdit Version

Forge-Official(7.2.10+1742f98

### Platform Version

forge

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

There is a bug in worldedit with /brush forest. When i do it, the trees stack on top of each other. It use to not do that with older versions. Please fix this.

### Expected Behavior

Trees stacking on top of each other when i use wand

### Reproduction Steps

1. ...
2. ...

**Comment by octylFractal** [comment] 2022-10-03 00:06
Duplicate of #2008

**Closed by octylFractal** 2022-10-03 00:06 UTC
Labels: type:bug, status:pending
