### ISSUE TITLE
//forest, /forestgen, /brush forest not working correctly

### ISSUE THREAD

**Issue by frederikvonand** [EngineHub/WorldEdit#2511] opened 2024-04-14 17:37 UTC
### WorldEdit Version

7.3.0

### Platform Version

WorldEdit 7.3.0 (Forge/Fabric for MC 1.20.4)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When using the command /brush forest junglebush, jungle bushes are produced, but not containing any type of tree log/wood inside, thus making the leaves decay.

When i try using //forest or /forestgen with junglebush, the same thing happens. If i do jungle, small_jungle or randjungle, only a few pieces of logs/wood spawns, making the tree half in size and the leaves decay.

### Expected Behavior

In previous versions, /brush forest would create jungle bushes with logs/wood inside, and trees with the correct amount of logs/wood.
The same for //forest and /forestgen

### Reproduction Steps

1. Do /brush forest cyl jungle_bush
2. Right-click on grass block

**Comment by octylFractal** [comment] 2024-04-14 17:47
Duplicate of #2508

**Closed by octylFractal** 2024-04-14 17:47 UTC
Labels: type:bug, status:pending
