### ISSUE TITLE
Please add some more editing commands.

### ISSUE THREAD

**Issue by bauerbach** [EngineHub/WorldEdit#1982] opened 2021-12-22 02:16 UTC
### The Problem

It would be nice if there were more editing commands. For example, to make a half-sphere/dome, I have to use //sphere and then manually cut off half of it. Also, it's hard to make a //generate command work only for every other block.

### A Solution

These commands would greatly improve WorldEdit:

//dome [-hr] <pattern> <radii> and //hdome [-hr] <pattern> <radii>: Works like //sphere and //hsphere respectively, but only creates half of a sphere.

//checkerboard <pattern1> <pattern2>: Works like //generate with a constant for the "expression..." argument, but alternates between pattern1 and pattern2. The command would also be able to be used with just pattern1, which ignores every other block.

Also, an argument should be added to //cyl, //hcyl, //pyramid, and //hpyramid that allows for rotation. This could also be applied to the aforementioned //dome and //hdome commands.

### Alternatives

A workaround to the lack of rotation in the //cyl, //hcyl, //pyramid, and //hpyramid commands is //rotate, but this can be a bit unpredictable as it involves using the clipboard. Also, there may be an expression for the //generate command for making checkerboard-like patterns, but it is very complex.

### Anything Else?

These new commands would make creating structures such as domes and tunnels much easier and quicker.

**Comment by octylFractal** [comment] 2021-12-22 02:21
Duplicate of #72 for //dome.

//checkerboard is pointless, you can just implement this in `//gen` yourself (there are boolean conditionals, you can assign the data -- it's not that complicated, plus determining which blocks should cause it to alternate is not so simple -- there are multiple ways to do it!). 1.13+ blocks are technically not supported yet because of #1269, so that also covers this request.

Rotating will be covered as per your alternative, duplicate of #1554.

**Closed by octylFractal** 2021-12-22 02:21 UTC
Labels: type:feature-request, status:pending
