### ISSUE TITLE
Manipulating region spawns duplicate items/blocks

### ISSUE THREAD

**Issue by Bloodlex** [EngineHub/WorldEdit#1934] opened 2021-11-12 08:48 UTC
### WorldEdit Version

7.2.7

### Platform Version

Purpur 1.17.1-R0.1-SNAPSHOT

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When copying and pasting selection or moving and doing other region manipulations, some duplicate blocks are dropped like lanterns, doors, torches, signs and others.

### Expected Behavior

Nothing should be dropped.

### Reproduction Steps

1. Select a region with lanterns, torches, signs.
2. Copy this region and paste somewhere, move or do anything that moves a region.
3. Duplicate items are dropped like lanterns, signs and so on.

**Comment by me4502** [comment] 2021-11-12 08:49
Test without Purpur, WorldEdit does not do this

**Comment by wizjany** [comment] 2021-11-12 14:39
can't repro.

**Comment by Bloodlex** [comment] 2021-11-12 20:35
@wizjany Does -e flag change anything on that?

**Comment by wizjany** [comment] 2021-11-12 20:36
Not sure why it would, torches/lanterns/etc aren't entities.

**Comment by octylFractal** [comment] 2021-11-12 20:41
I tested on latest Paper for fun, and indeed the signs do _not_ drop with `-e`. If you can reproduce _on Paper_, please show the exact region you're using, perhaps there's an edge-case that we aren't able to see.

**Comment by octylFractal** [comment] 2021-11-12 20:52
Okay, this issue had murky reproduction steps, but I think I found the issue. `//move` or perhaps _`//cut`_, but not a _copy_, will sometimes cause item drops where blocks were removed. This can be avoided by using `//perf neighbors off`, but realistically should be handled better. Likely also fixed in 7.3 due to `//reorder fast` now being the default, which also delays these updates until after the edit is fully complete. Perhaps we should consider changing it in 7.2.x, if possible.

**Comment by Bloodlex** [comment] 2021-11-12 20:59
> Okay, this issue had murky reproduction steps, but I think I found the issue. `//move` or perhaps _`//cut`_, but not a _copy_, will sometimes cause item drops where blocks were removed. This can be avoided by using `//perf neighbors off`, but realistically should be handled better. Likely also fixed in 7.3 due to `//reorder fast` now being the default, which also delays these updates until after the edit is fully complete. Perhaps we should consider changing it in 7.2.x, if possible.

Yes, sorry I haven't described it better. I'd really like to see it fixed, because this can happen sometimes to drop of many, really many items being dropped on the ground with large cuts and pastes. I'm not sure which other operations are affected, I thought it may be also //stack and similar.

Thanks very much.

**Comment by Bloodlex** [comment] 2021-11-12 21:15
> Okay, this issue had murky reproduction steps, but I think I found the issue. `//move` or perhaps _`//cut`_, but not a _copy_, will sometimes cause item drops where blocks were removed. This can be avoided by using `//perf neighbors off`, but realistically should be handled better. Likely also fixed in 7.3 due to `//reorder fast` now being the default, which also delays these updates until after the edit is fully complete. Perhaps we should consider changing it in 7.2.x, if possible.

When using //perf neighbors off, for instance lanterns are not pasted after cutting no matter if -e is used or not 🙁 .

**Comment by octylFractal** [comment] 2021-11-13 03:42
I cannot reproduce that. Are you testing on Paper?

**Comment by Bloodlex** [comment] 2021-11-13 11:37
> I cannot reproduce that. Are you testing on Paper?

Right now I've tested that on Purpur. What actually this option //perf neighbors off should do?

**Comment by octylFractal** [comment] 2021-11-13 16:39
It simply stops firing the neighbors updates when setting blocks. It shouldn't affect what WorldEdit copies or pastes, that sounds like a problem with Purpur.

**Comment by octylFractal** [comment] 2024-11-04 05:03
I think we fixed this in 7.3.0.

**Closed by octylFractal** 2024-11-04 05:03 UTC
Labels: type:bug, status:accepted
