### ISSUE TITLE
All collumns biome change option (ex: //setbiome swamp -all

### ISSUE THREAD

**Issue by MaybeJulien** [EngineHub/WorldEdit#1523] opened 2020-09-08 13:52 UTC
**Is your feature request related to a problem? Please describe.**
Since in the beta of 1.16.1-1.16.2 now if you want to do //setbiome you have to select blocks in a 3d manner it would be useful to have an option to do it the same way it used to be where you only selected blocks where you wanted the biome to be and it would change the entire column.

**Describe the solution you'd like**
something like //setbiome swamp -all
could maybe set the biome in all the columns selected

**Describe alternatives you've considered**
I have not considered any other option

**Additional context**
When i changed version it took me about 2h to figure out what was going on so adding that option would also help people switching from versions.

**Comment by me4502** [comment] 2020-09-08 13:55
Duplicate of https://github.com/EngineHub/WorldEdit/issues/1435

**Closed by me4502** 2020-09-08 13:55 UTC
Labels: status:pending, type:feature-request
