### ISSUE TITLE
"This WorldEdit version does not fully support your version of Bukkit."

### ISSUE THREAD

**Issue by AkZydro** [EngineHub/WorldEdit#2647] opened 2024-10-21 10:11 UTC
### WorldEdit Version

7.3.7

### Platform Version

Paper version 1.21.1-127-master@14a48cd

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I launch my server, I get this in my logs :

[Server thread/WARN]:
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
**  When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and block property-related functions.
** 
** Please see https://worldedit.enginehub.org/en/latest/faq/#bukkit-adapters
**********************************************

Whereas I have the most recent version of Paper and WorldEdit... I can't use the commands.

### Expected Behavior

I want this message not appears and I want to be able to use the plugin.

### Reproduction Steps

Just launch the server.

**Comment by Joo200** [comment] 2024-10-21 10:15
Duplicate of #2646

**Closed** 2024-10-21 10:51 UTC
Labels: type:bug, status:invalid
