### ISSUE TITLE
//undo breaks redstone components

### ISSUE THREAD

**Issue by fIREmiNeR1** [EngineHub/WorldEdit#2563] opened 2024-06-28 05:38 UTC
### WorldEdit Version

7.2.10

### Platform Version

Fabric 1.18.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

After pasting a schematic in the world, and doing //undo, redstone components at the area where schematic was pasted, are broken.

### Expected Behavior

After pasting clipboard and doing //undo, the area where schematic was pasted is the same as before pasting.

### Reproduction Steps

1. Load any schematic
2. Paste it in the area with redstone components(redstone dust, repeaters, comparators, torches)
3. //undo

**Comment by octylFractal** [comment] 2024-06-28 05:39
Duplicate of #2516

**Closed by octylFractal** 2024-06-28 05:39 UTC
Labels: type:bug, status:pending
