### ISSUE TITLE
Tool left click range is limited

### ISSUE THREAD

**Issue by erraineon** [EngineHub/WorldEdit#1549] opened 2020-10-03 23:23 UTC
**Versions**

WorldEdit version: Forge-Official (7.2.0-beta-05+20b3da4)
Platform version: Forge 34.0.17 on minecraft 1.16.3

**Describe the bug**
Left clicking in a forge server with the compass or the far wand only swings the tool and doesn't trigger its effect outside of the "normal" tool's range.

**To Reproduce**

1. Start the minecraft forge server.
2. Start the minecraft client.
3. Connect to the server.
4. Type /farwand to obtain the far wand tool.
5. Left click on a distant block to set the selection (not too far, still within the expected far wand range).
6. The tool will swing but no selection will be set.
7. Right click on the same block to set the selection.
8. Pos2 will be set successfully.

**Expected behavior**
Both left and right click should set the selection with the far wand on far away blocks. Same goes for using the compass.

**Screenshots**
![image](https://user-images.githubusercontent.com/35406749/95003015-8e00e500-05a8-11eb-940d-3570014dee54.png)

**Additional context**
When I log on single player and enable the far wand, it then works in multiplayer as well until I restart the client. So that's a work around for now.

**Comment by octylFractal** [comment] 2021-01-03 20:54
Duplicate of #1439

**Closed by octylFractal** 2021-01-03 20:54 UTC
Labels: status:pending, type:bug
