### ISSUE TITLE
Port of Curseforge Modpack doesn't work on MultiMC: Caused by Worldedit

### ISSUE THREAD

**Issue by Razatop** [EngineHub/WorldEdit#1692] opened 2021-03-06 19:07 UTC
**Versions**
WorldEdit version:worldedit-mod-7.2.3
Platform version: forge-36.0.46

**Describe the bug**
Ported my friends and I current private modpack to MultiMC (Because I/We prefer it) and it ends up crashing when trying to create/load into a singleplayer world (Haven't tested Multiplayer, haven't got around to making a server for it) The end of the log reads something about immersive engineering but even after removing that the problem still happens. I also reinstalled MultiMC to see if that was the issue, did not fix it.

[Link to the MultiMC Github issue here](https://github.com/MultiMC/MultiMC5/issues/3641)

**To Reproduce**

1. Download our Modpack TestCraft (if needed)
2.Import to MultiMC
3.Launch and try to create a world only to encounter linked at the bottom of the issue page.

**Expected behavior**
World should load up without incident much like it does on the Curseforge launcher.

**Screenshots**
N/A

**Additional context**
[Link to the Log after crash](https://paste.ee/p/vSlVS)

**Comment by octylFractal** [comment] 2021-03-06 19:10
Duplicate of #1398

**Closed by octylFractal** 2021-03-06 19:10 UTC
Labels: status:pending, type:bug

**Comment by Razatop** [comment] 2021-03-06 19:11
> Duplicate of #1398

So from what I'm seeing there is no fix for this at the current moment at all, both you and someone on the MultiMC github lead me to that issue and it seems like the only option is to continue using curseforge.

**Comment by octylFractal** [comment] 2021-03-06 19:16
The best fix is to rollback to 7.2.2. If you can't do that, then there is no fix.
