### ISSUE TITLE
Redstone breaks when using //move

### ISSUE THREAD

**Issue by IPlayMinecraftYT** [EngineHub/WorldEdit#2568] opened 2024-07-05 00:06 UTC
### WorldEdit Version

7.3.3

### Platform Version

Fabric 0.15.11

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Using //move on a selected area with redstone it breaks (the redstone drops as items) all the redstone except for the piece at the lowest x and y position

### Expected Behavior

It should not break the redstone

### Reproduction Steps

1. select a horizontal area with more than 1 redstone 
2. use //move to move it in any horizontal direction

### Anything Else?

I'm assuming that worldedit loops through all the redstone with a for loop in both the x and z directions, but it stops after the first loop and breaks all the other redstone. This happens for each vertical slice (each y value). However for some reason it breaks completely random pieces of redstone, and the only thing that is the same between all of it is that there will only be one piece of redstone left.

Notably I am running on a server with no other mods installed.

**Comment by octylFractal** [comment] 2024-07-05 00:16
Duplicate of #2516

**Closed by octylFractal** 2024-07-05 00:16 UTC
Labels: type:bug, status:pending

**Comment by IPlayMinecraftYT** [comment] 2024-07-05 00:52
Not a duplicate of #2516, //stack and //paste work fine

**Comment by octylFractal** [comment] 2024-07-05 00:54
They're all the same code so unless something very weird is going on, it's the same issue. The exact way to cause it can be unreliable to trigger.
