### ISSUE TITLE
WorldEdit not work on Sponge 1.16.5

### ISSUE THREAD

**Issue by R3bolution** [EngineHub/WorldEdit#2129] opened 2022-06-27 16:46 UTC
### WorldEdit Version

7.2.9+e20e013

### Platform Version

spongeforge-1.16.5-36.2.5-8.1.0-RC1153

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

when my server started it gives me an error

### Expected Behavior

Dont work

### Reproduction Steps

1. Start the server

### Anything Else?

![image](https://user-images.githubusercontent.com/98266150/175993003-3547b107-f754-46c2-bde0-0ac9f735b89d.png)

**Comment by octylFractal** [comment] 2022-06-27 18:20
Duplicate of #2106

**Closed by octylFractal** 2022-06-27 18:20 UTC
Labels: type:bug, status:pending
