### ISSUE TITLE
Issue with the /copy command

### ISSUE THREAD

**Issue by darkknight588** [EngineHub/WorldEdit#2430] opened 2023-10-29 21:40 UTC
### WorldEdit Version

7.3.0

### Platform Version

Spigot

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I am trying to copy a selection and I keep getting an error. I am unsure what it means but I had tried to save the selection as a schematic earlier and it was failing to load them properly

### Expected Behavior

the clipboard to be copies

### Reproduction Steps

1. ...//copy
2. ...
<img width="1512" alt="Screenshot 2023-10-29 at 5 00 46 PM" src="https://github.com/EngineHub/WorldEdit/assets/149335130/c7cdcc52-40fb-4e7a-8fc9-fd0d42d9f734">

### Anything Else?

[](url)
<img width="1512" alt="Screenshot 2023-10-29 at 5 00 46 PM" src="https://github.com/EngineHub/WorldEdit/assets/149335130/390846ac-40c7-4fdd-a2a3-3dc5619260a8">

**Comment by octylFractal** [comment] 2023-10-29 21:43
7.3.0 is not a valid version yet, please include the full version information. Also, include youyt Minecraft version.

**Comment by me4502** [comment] 2023-11-04 06:25
I cannot reproduce this, given you didn't provide what Spigot version you're using you're likely on a very old version that was broken.

**Comment by Boredflea** [comment] 2023-11-04 14:43
It was the beta version 3.0.0 and I switched to the current version

**Comment by Boredflea** [comment] 2023-11-04 14:44
Sorry to intrude but 7.3.0 is the beta version and is on the built page

**Comment by me4502** [comment] 2023-11-04 15:20
That’s not the spigot version

**Comment by Boredflea** [comment] 2023-11-04 15:28
Ok

**Comment by Boredflea** [comment] 2023-11-04 15:29
I just believe that he said that it was 7.3.0 in his request

**Comment by BonfireTheOtter** [comment] 2023-11-11 20:19
I have exactly this issue. it is caused when blocks can be in different states (chests having inventories, and comparators) it means that it is trying to access something it cant (i think??). I dont have a fix tho. same set up, 7.3.0 beta, spigot

**Comment by octylFractal** [comment] 2023-11-11 20:48
Again, we need the the exact Spigot version you're using.

**Comment by StoneCrusher679** [comment] 2024-01-24 20:24
I have the exact same issue, it seems to be with anything that stores data. So signs, lecturns, chests, NBT stuff. This was the error it gave: https://mclo.gs/MKBzZLK
I'm using WorldEdit 7.3.0-beta-03 with Spigot 1.20.4 (4026)

**Comment by wizjany** [comment] 2024-01-24 20:51
dupe of #2450

**Closed by wizjany** 2024-01-24 20:51 UTC
Labels: type:bug, status:pending
