### ISSUE TITLE
WorldEdit told me to report this error

### ISSUE THREAD

**Issue by EnolaK64** [EngineHub/WorldEdit#2598] opened 2024-08-09 11:45 UTC
### WorldEdit Version

7.3.5

### Platform Version

Fabric-Official(7.3.5+6880-8ba3d89)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

[13:34:52] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.util.concurrent.RejectedExecutionException: Task TrustedListenableFutureTask@17dc774[status=PENDING, info=[task=[running=[NOT STARTED YET], com.sk89q.worldedit.command.util.AsyncCommandBuilder$$Lambda/0x00000182825acb88@3f62108d]]] rejected from java.util.concurrent.ThreadPoolExecutor@6538ca02[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source) ~[?:?]
	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:640) ~[guava-32.1.2-jre.jar:?]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source) ~[?:?]
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:79) ~[guava-32.1.2-jre.jar:?]
	at com.sk89q.worldedit.command.util.AsyncCommandBuilder.buildAndExec(AsyncCommandBuilder.java:139) ~[worldedit-mod-7.3.5.jar:?]
	at com.sk89q.worldedit.command.util.WorldEditAsyncCommandBuilder.createAndSendMessage(WorldEditAsyncCommandBuilder.java:50) ~[worldedit-mod-7.3.5.jar:?]
	at com.sk89q.worldedit.command.SchematicCommands.list(SchematicCommands.java:333) ~[worldedit-mod-7.3.5.jar:?]
	at com.sk89q.worldedit.command.SchematicCommandsRegistration.cmd$list(SchematicCommandsRegistration.java:268) ~[worldedit-mod-7.3.5.jar:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-mod-7.3.5.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:506) ~[worldedit-mod-7.3.5.jar:?]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-mod-7.3.5.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-mod-7.3.5.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-mod-7.3.5.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-mod-7.3.5.jar:?]
	at com.sk89q.worldedit.fabric.CommandWrapper.lambda$register$0(CommandWrapper.java:62) ~[worldedit-mod-7.3.5.jar:?]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.class_8865.method_54416(class_8865.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_8865.execute(class_8865.java:13) ~[client-intermediary.jar:?]
	at net.minecraft.class_8856.method_54405(class_8856.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_8847.method_54388(class_8847.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_8854.method_54390(class_8854.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_2170.method_54313(class_2170.java:379) ~[client-intermediary.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_58590(class_3244.java:1319) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_44356(class_3244.java:1307) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]

### Expected Behavior

I expected to see a list of all available structures to load

### Reproduction Steps

on Paper Server:
1. //copy
2. //schem save [fileName] schem
3. change world to local world (instead of server)
4. //schem list

**Comment by me4502** [comment] 2024-08-09 11:46
duplicate of https://github.com/EngineHub/WorldEdit/issues/2586

**Closed by me4502** 2024-08-09 11:46 UTC
Labels: type:bug, status:pending
