### ISSUE TITLE
Schematic from old version signs

### ISSUE THREAD

**Issue by Maximillus** [EngineHub/WorldEdit#1533] opened 2020-09-18 20:08 UTC
**Versions**

WorldEdit version: WorldEdit 7.2.0 Beta 5 (1.13.2 - 1.16.3)
Platform version: 1.15.2

**Describe the bug**

When loading schematic from 1.8 into 1.15.2 all of the sign have empty normal will have "..." on each line.
**To Reproduce**

1. ... take schematic on the 1.8 version with empty signs
2. ...paste the schematic in 1.15 version

**Expected behavior**
empty sign
**Screenshots**
![image](https://user-images.githubusercontent.com/2093023/93641273-dc12c780-f9b0-11ea-874e-5639fef8e11a.png)

**Additional context**
there nothing else to say. Thank you

**Comment by octylFractal** [comment] 2020-09-18 20:44
If I recall correctly, those aren't dots, they're quotation marks, i.e. `""`. I think this issue has been mentioned before, but I can't seem to find where, and I also can't reproduce. Can you provide a schematic that causes this?

**Comment by wizjany** [comment] 2020-09-27 13:07
closing unless we get repro.

**Closed by wizjany** 2020-09-27 13:07 UTC
Labels: status:invalid, type:bug
