### ISSUE TITLE
inverse for //smooth? smoothing the wrong way

### ISSUE THREAD

**Issue by Charcoal87** [EngineHub/WorldEdit#1470] opened 2020-08-06 08:32 UTC
**Versions**

WorldEdit version: 6.1.10-SNAPSHOT
Platform version: MC Forge 14.23.5.2847

**Describe the bug**
In one of my build worlds, I have a floating island that, at the bottom, I'm trying to smooth out. However, when I make a cubic region around the bottom and type the command, It smooths in the opposite way. I don't know if this is intended or not but I'm using the bug report section to report this. The brush tool won't work either.

**To Reproduce**

1. Make a cubic region around the bottom of my island
2. //smooth 50

**Expected behavior**
I expected it to smooth but not sure which way. I couldn't find a way online to invert the smoothing.

**Screenshots**
![2020-08-06_03 23 02](https://user-images.githubusercontent.com/36941503/89509232-ac0ebc80-d794-11ea-9214-bf13abf10c84.png)

![2020-08-06_03 23 22](https://user-images.githubusercontent.com/36941503/89509267-b9c44200-d794-11ea-88e3-e4ef386dbd7c.png)

**Additional context**
Really all I'm looking for is to see if there is a way to invert the smoothing.

**Comment by wizjany** [comment] 2020-08-06 13:35
smooth always smooths the top of the area. this is a feature request and duplicate of #1145 
note that old versions won't receive new features anyway. your best bet may be to make a flipped copy and smooth that, then flip back.

**Closed by wizjany** 2020-08-06 13:35 UTC
Labels: status:pending, type:bug

**Comment by Charcoal87** [comment] 2020-08-06 19:08
> smooth always smooths the top of the area. this is a feature request and duplicate of #1145
> note that old versions won't receive new features anyway. your best bet may be to make a flipped copy and smooth that, then flip back.

Ah, I see. Thanks, man, I didn't see that 1145 post.
