### ISSUE TITLE
Conflict with fabric-carpet

### ISSUE THREAD

**Issue by octylFractal** [EngineHub/WorldEdit#1605] opened 2020-12-10 20:44 UTC
**Versions**
WorldEdit version: 7.2.1
Platform version: 1.16.3+

**Describe the bug**
WorldEdit's UPDATE mixin conflicts with fabric-carpet's same mixin, crashing the game.

**To Reproduce**
1. Install both mods.
2. Launch the game.

**Expected behavior**
The two mods should work together.

**Workaround**
Downgrade to 7.2.0, no UPDATE mixin -> no conflict.

**Comment by RDKRACZ** [comment] 2020-12-11 10:59
Weird, I can run Carpet and WorldEdit mod without crash **but** when I add Library of Exile to mods then mc crashes.
Running Library of Exile with WorldEdit without Carpet doesn't crash.

**Comment by RDKRACZ** [comment] 2020-12-11 11:00
![Screen Capture_20201211115819](https://user-images.githubusercontent.com/43277609/101895863-63369c80-3ba8-11eb-9032-9ff1319d93fc.png)

**Comment by RDKRACZ** [comment] 2020-12-11 11:05
https://github.com/gnembon/fabric-carpet/issues/625
https://github.com/RobertSkalko/Library-of-Exile/issues/1

**Comment by RDKRACZ** [comment] 2020-12-11 11:06
https://github.com/gnembon/fabric-carpet/issues/625

**Comment by RDKRACZ** [comment] 2020-12-11 11:07
https://github.com/RobertSkalko/Library-of-Exile/issues/1

**Comment by BBloom81** [comment] 2020-12-14 01:49
Confirmed here as well.

Carpet 1.4.20 with WorldEdit 7.2.1 crashes game when loading world.
Remove either and no issues.

**Comment by wizjany** [comment] 2020-12-14 01:50
don't need additional confirmation, note the accepted label.

**Comment by altrisi** [comment] 2020-12-17 04:53
A question is whether when this is fixed, will both features (`fillUpdates` from Carpet and WE's editing without updates) work together? Like, if someone disables updates in Carpet, WE won't force updates if WE updates are on, and the other way around. 

Or will this be fixed by letting one of the features dominate the other? (with Carpet probably already offering the without updates functionality for WE since they are based on the same spot and it being more general)

**Comment by octylFractal** [comment] 2020-12-17 05:33
Don't know yet, I think the only viable solutions I know of now is either:
a) WorldEdit drops UPDATE support on Fabric if Carpet is installed (we will probably implement this temporarily at least) 
b) Carpet drops fillUpdates if WorldEdit is installed (up to them)
c) It becomes Fabric API, and effectively forces Carpet to accommodate/use the API mixin (this is tentatively possible)

We will not add special handling for Carpet in particular, we would just be checking mixin targets.

**Comment by Ghoulboy78** [comment] 2020-12-26 13:30
cant WE just change mixin priority so that either in case of conflict there isnt any ambiguity?

**Comment by Ghoulboy78** [comment] 2020-12-26 13:35
Because gnembon(owner of fabric carpet repo ) would likely be wiling to do that if necessary. But specifically checking for WE likely wouldnt be very neat in the code, not to mention that WE may not be the only mod with such conflicts, so I suppose that mixin manipulation would be best. Looking at the three options, it seems that the only thing now is to decide who does it... I know gnembon doesnt want to use fabric API for sure.

**Comment by octylFractal** [comment] 2021-01-04 18:36
> cant WE just change mixin priority so that either in case of conflict there isnt any ambiguity?
To my knowledge, no, though I would be happy to be proven wrong. I've asked and gotten no solution.

**Comment by me4502** [comment] 2021-01-28 08:04
Closing as fixed in https://github.com/EngineHub/WorldEdit/commit/56c891946ddbd380990d46a1ca89d86c228b4ffa

(Assume it didn't auto-close due to not being master)

**Closed by me4502** 2021-01-28 08:04 UTC
Labels: platform:fabric, status:accepted, type:bug
