### ISSUE TITLE
Reload struggles SinglePlayer

### ISSUE THREAD

**Issue by Helfrnd** [EngineHub/WorldEdit#1626] opened 2020-12-26 22:02 UTC
**Versions**
WorldEdit version: Latest (7.2.1)
Platform version: 1.16.4 (Optifine 1.16.4 U G5)
Edit: Forge (forge-1.16.4-35.1.13)

**Describe the bug**
Short and crisp, the usage of /reload in Singleplayer disables all commands (fixed by reopening world)

**To Reproduce**
1. Create a world, doesn't matter which type
2. Use /reload
3. Try using any of the // commands

**Expected behavior**
Using a // command (Autocompletion, etc.)

**Screenshots**
![2020-12-26_23 00 23](https://user-images.githubusercontent.com/76631755/103159821-4916d400-47ce-11eb-8365-6b03e1384f16.png)

**Additional context**
---

**Comment by SnaveSutit** [comment] 2021-05-23 18:15
I am also having this issue on my Multiplayer server. After reloading none of the World Edit commands are accessible.


WorldEdit: 7.2.5
Forge: 36.1.23
Minecraft 1.16.5

**Comment by wizjany** [comment] 2021-05-23 18:16
the issue is accepted, we don't need further confirmations thanks.

**Comment by SnaveSutit** [comment] 2021-05-24 13:53
I was only confirming that this issue also happened on multiplayer servers, and in the latest version of world edit.

**Comment by wizjany** [comment] 2021-05-24 13:56
unless we had somewhere said that this was fixed in between the original version and your version, then it is expected that the bug is still present. also yes, worldedit only runs on the server-side as do all minecraft commands, like reload.

**Comment by wizjany** [comment] 2021-07-26 02:46
#1766 closes this iirc

**Closed by wizjany** 2021-07-26 02:46 UTC
Labels: platform:forge, status:accepted, type:bug

**Comment by wizjany** [comment] 2021-10-16 15:20
this is fixed in current versions. we don't have the time or motivation to backport everything to old versions. feel free to backport and PR to the archive branch, but we won't be doing more releases for old versions.
