### ISSUE TITLE
Regen region doesn't work

### ISSUE THREAD

**Issue by VL4DST3R** [EngineHub/WorldEdit#1544] opened 2020-10-01 22:00 UTC
**Versions**

WorldEdit version:
------------------ Platforms ------------------
Bukkit-Official(7.2.0-beta-05+e575ffe)
---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

Platform version:
Server version: 1.16.1-R0.1-SNAPSHOT git-Paper-138 (MC: 1.16.1)

**Describe the bug**
making a selection (pos1 pos2) and using //regen on my survival map erases everything in the selection instead of actually regenerating the area, without any error (thankfully i can undo it)

**To Reproduce**

1. make selection
2. do //regen
3. notice the now complete lack of blocks inside your selection

**Expected behavior**
regenerate the landscape/area as it was before player intervention

**Screenshots**
not really needed?

**Additional context**
i do have other mods installed, but i can't see why it would affect/interfere with worldedit. If i had to guess stuff like Multiverse, EssentialsX and CoreProtect could _maybe_ interfere? I am the admin and have full permissions to do anything so i doubt its a permission issue. Doing /seed also reports the correct seed of the map, so it's not like Worldedit has no idea what seed to populate the area with.

Another thing to note though, if i do //regen on my creative flat world, it actually regens the area correctly (to the flat grass generator settings i have for it)

**Comment by wizjany** [comment] 2020-10-01 22:04
sounds a lot like you have a custom world gen returning an empty chunk there. the fact that it works on another world highly suggests that everything is fine on WE's end. would suggest you try to reproduce without other plugins, especially those that mess with worlds/worldgen.

**Comment by VL4DST3R** [comment] 2020-10-01 22:06
I have no custom worldgens installed at all. Even so, is there a way to check? Would the level.dat have anything related to it?

**Comment by octylFractal** [comment] 2020-10-09 02:16
Can you reproduce this on 1.16.3? If it's not reproducible or there's no response by the end of October, we'll close this as can't reproduce.

If you don't have custom worldgen installed, there shouldn't be any custom worldgen. WorldEdit has no known issues with multiverse.

**Comment by VL4DST3R** [comment] 2020-10-09 11:31
My server and users are still on 1.16.1. We're waiting for a few mods to finally decide to update to .3 so we can switch, but it didn't happen yet, so sadly i can't test this until then.

**Comment by jadar** [comment] 2020-11-10 17:30
I am having this issue on Spigot 1.16.3, as well. Still doesn't work when I've removed all of my world gen/protection plugins. Any more insights?

**Comment by octylFractal** [comment] 2020-11-10 17:49
Can you provide your logs?

**Comment by jadar** [comment] 2020-11-10 17:53
Sure!

```[16:42:11] [Server thread/INFO]: <redacted> issued server command: //regen
[16:42:11] [Server thread/WARN]: Regeneration via adapter failed.
java.lang.UnsupportedOperationException: Missing BukkitImplAdapater for this version.
        at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:185) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommands.regenerateChunk(RegionCommands.java:415) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:568) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:486) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:348) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:758) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-17d78db-2577f9b]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[17:52:30] [Server thread/INFO]: Plugins (7): LuckPerms, WorldEdit, Vault, ChestShop, Essentials, EssentialsAntiBuild, SinglePlayerSleep
```

**Comment by octylFractal** [comment] 2020-11-10 17:54
That is a different issue, you probably need to update to WorldEdit 7.2.0.

**Comment by wizjany** [comment] 2020-11-10 17:58
also since october is over gonna follow through and close this as we couldn't repro the original issue.

**Closed by wizjany** 2020-11-10 17:58 UTC
Labels: status:pending, type:bug

**Comment by jadar** [comment] 2020-11-10 18:07
> That is a different issue, you probably need to update to WorldEdit 7.2.0.

Thanks. That worked!

**Comment by jeremy-rifkin** [comment] 2023-03-19 02:19
Running into this issue with 7.2.13 and spigot 1.19.4

**Comment by me4502** [comment] 2023-03-19 02:20
Use a version that supports 1.19.4, don’t comment on old issues
